### ISSUE TITLE
Enqueue JS file small bug

### ISSUE THREAD

**Issue by Wooody82** [renventura/wp-delete-user-accounts#1]
Hi,
Thanks for your code :) , There is just small fix
To enqueue the wp-delete-user-accounts-js file: u used array( 'jquery', 'sweetalert' ) but it should be array( 'jquery', 'sweetalert-js' ) like this:
`wp_enqueue_script( 'wp-delete-user-accounts-js', WP_DELETE_USER_ACCOUNTS_PLUGIN_URL . 'assets/js/wp-delete-user-accounts.js', array( 'jquery', 'sweetalert-js' ), WP_DELETE_USER_ACCOUNTS_VERSION, true );
`

**Comment by renventura** [comment]
Hey @malasaad82. Ahh, good catch! Thanks for the report. I'll get this updated.

**Comment by Wooody82** [comment]
No problem :)
