### ISSUE TITLE
is_readable() error 

### ISSUE THREAD

**Issue by kompuser** [renventura/wp-delete-user-accounts#2]
Hi 
I noticed a recurring error on my server logs (hosted on kinsta.com).

`open_basedir restriction in effect. File(/www/thehostbasedirectory/public/wp-content/plugins/wp-delete-user-accounts/wp-delete-user-accounts.php/languages/wp-delete-user-accounts-en_GB.mo) is not within the allowed path(s)`

It looks like the plugin is looking for for the following directory but this doesn't exists : 
`/thehostbasedirectory/public/wp-content/plugins/wp-delete-user-accounts/wp-delete-user-accounts.php/languages/`

And the error comes from .php extension that is appended to the directory name.

**Comment by renventura** [comment]
Thanks for the report, @kompuser  - I fixed this one in the latest release. Test it out, and please let me know if the update resolves everything for you.
