### ISSUE TITLE
WP_Delete_User_Accounts loads wrong admin.php

### ISSUE THREAD

**Issue by arminus** [renventura/wp-delete-user-accounts#3]
Effect: Delete Account button doesn't show up at all in profile page.

Cause: In my server installation, WP_Delete_User_Accounts:includes() apparently doesn't load (the correct?) includes/admin.php. I took my a while to figure this out, since the plugin works ok in my local dev environment (XAMPP on Windows) but not on the production server. 

Renaming includes/admin.php to includes/myadmin.php (and changing the respective include_once) solves the problem in my installation. I'm no PHP export, so I have no idea why this might happen - and only on my server installation which is an exact copy of what I have in my dev env...

**Comment by renventura** [comment]
Hi @arminus,

That's strange. Who is your hosting provider?

Ren

**Comment by arminus** [comment]
strato.de - and I have no problem on that site with any other plugin.

**Comment by renventura** [comment]
@arminus I've seen situations where hosts don't like certain file names. Since you're able to get this to work by changing the file name, I'm wondering if that may be the case here.

**Comment by arminus** [comment]
@renventura meanwhile I've tested this in a local Linux VM (Ubuntu 14.04.5 LTS) - same issue. On this box, I can give you all details you might need.

> I've seen situations where hosts don't like certain file names

Under which conditions?

Also, I have the following in my installation:
```
find . -name admin.php -print
./wp-admin/network/admin.php
./wp-admin/admin.php
./wp-admin/includes/admin.php
./wp-admin/user/admin.php
./wp-content/plugins/wp-delete-user-accounts/includes/admin.php
```

Since wp-admin/admin.php is in another base path, I guess the relative include can't be conflicted here either?
